// Generated by CoffeeScript 1.6.3
'# import the Connect middleware (http://www.senchalabs.org/connect/)\nconnect = require(\'connect\')\n\n# create a Connect server\nserver = connect()\n# attach a static file server that serves files from our static directory\nserver.use(connect[\'static\'](__dirname + "/../static"))\n\n# set our server port and start the server\nport = 5000\nserver.listen(port, () -> console.log("Listening on " + port))';
var ShareJS, ShareJSOpts, connect, port, server;

connect = require('connect');

ShareJS = require('share').server;

ShareJSOpts = {
  browserChannel: {
    cors: "*"
  },
  db: {
    type: "none"
  }
};

server = connect();

server.use(connect['static'](__dirname + "/../static"));

ShareJS.attach(server, ShareJSOpts);

port = 5000;

server.listen(port, function() {
  return console.log("Listening on " + port);
});
